- hosts: webserver
  tasks:
  - name: "Installing httpd package"
    package:
      name: "httpd"
      state: present
  - name: "Copying the Webpage"
    copy:
      dest: "/var/www/html/index.html"
      content: "Hello, My Webserver is running.  \n "

  - name: "Starting the Web service"
    service:
      name: "httpd"
      state: started
  - name: "Creating a Firewall Rule"
    firewalld:
      port: "80/tcp"
      permanent: true
      immediate: true
      state: enabled


- hosts: haproxy 
  tasks:  
  - name: "Installing Haproxy"
    package:
         name: "haproxy"
         state: present
           - name: "Copy the configuration file"
    template:
       src: "/root/ansible_wp/haproxy.cfg"
       dest: "/etc/haproxy/"
  - name: "Start the services"
    service:
        name: "haproxy"
        state: restarted
  - name: "Creating a Firewall Rule"
    firewalld:
        port: "8080/tcp"
        permanent: true
        immediate: true
        state: enabled
      
      
         
   
   
